#!/bin/sh
# Xsetup - run as root before the login dialog appears

xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --rate 144 --output eDP-1-1 --mode 1920x1080 --pos 0x0 --rotate normal --rate 120
